<?xml version="1.0"?>
<?xml-model
  href="http://download.ros.org/schema/package_format3.xsd"
  schematypens="http://www.w3.org/2001/XMLSchema"?>

<package format="3">

  <name>insta360_usb_cam</name>
  <version>0.0.0</version>

  <description>
    Insta360 USB camera ROS2 package
  </description>

  <maintainer email="your_email@example.com">
    kdh
  </maintainer>

  <license>Apache-2.0</license>


  <!-- Build Tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>


  <!-- ROS2 -->
  <depend>rclcpp</depend>

  <depend>rclcpp_lifecycle</depend>
  <depend>lifecycle_msgs</depend>

  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>

  <depend>cv_bridge</depend>


  <!-- Custom Message -->
  <build_depend>
    rosidl_default_generators
  </build_depend>

  <exec_depend>
    rosidl_default_runtime
  </exec_depend>

  <member_of_group>
    rosidl_interface_packages
  </member_of_group>


  <!-- Launch -->
  <exec_depend>
    ros2launch
  </exec_depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>